---
- hosts: doorputer.s
  pre_tasks:
  - name: Detect chroot
    set_fact:
      chroot: "{{ ansible_connection == 'chroot' or 'container' in ansible_env }}"
    tags: always
  - name: Load secrets
    include_vars: 'secrets.yml'
    ignore_errors: yes
    tags: always
  roles:
  - doorputer

# vim: set ts=2 sw=2 et:
