---
- hosts: jumbotron.s
  pre_tasks:
  - name: Detect chroot
    set_fact:
      chroot: "{{ ansible_connection == 'chroot' or 'container' in ansible_env }}"
    tags: always
  roles:
  - jumbotron

# vim: set ts=2 sw=2 et:
