---
- hosts: mail1.labitat.dk
  pre_tasks:
  - name: Detect chroot
    set_fact:
      chroot: "{{ ansible_connection == 'chroot' or 'container' in ansible_env }}"
    tags: always
  roles:
  - mail1

# vim: set ts=2 sw=2 et:
