---
- hosts: space.labitat.dk
  pre_tasks:
  - name: Detect chroot
    set_fact:
      chroot: "{{ ansible_connection == 'chroot' or 'container' in ansible_env }}"
    tags: always
  - name: Load secrets
    include_vars: '{{ item }}'
    with_first_found:
    - secrets.yml
    - /root/secrets.yml
    ignore_errors: yes
    tags: always
  roles:
  - space_server

# vim: set ts=2 sw=2 et:
