---
- name: esmil - copy dotfiles
  copy:
    dest: '~esmil/.{{ item }}'
    src: 'esmil/{{ item }}'
    owner: esmil
    group: users
    mode: 0644
  with_items:
  - bash_profile
  - bashrc
  - bashrc_root
  - gitconfig

# vim: set ts=2 sw=2 et:
