---
- name: root - dotfiles
  copy:
    dest: '~root/.{{ item }}'
    src: 'root/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - bash_profile
  - bashrc

# vim: set ts=2 sw=2 et:
