---
hostname: 'doorputer'

users:
  'esmil': sudo
  'ast': sudo
  'flummer': sudo
  'riiiis': sudo
  'knielsen': sudo
  'signout': sudo

apt_sources:
  raspbian:
    components:
    - main
    - contrib
    - non-free
    - rpi

apt_packages:
  'git': present # to check out lockserver repo

  # lockserver dependencies
  'python3-serial': present
  'sqlite3': present

lockserver_conf:
  'Database.Path': '/home/doorman/users.db'
  'Serial.Device': '/dev/ttyUSB0'
  'Daymode.GPIONumber': '2'

# vim: set ts=2 sw=2 et:
