---
- name: Install dhcpd package
  dnf:
    name: dhcp-server
    state: latest
  notify:
    - restart dhcpd
  tags:
    - packages

- name: Configure dhcpd
  template:
    src: dhcpd/dhcpd.conf.j2
    dest: '/etc/dhcp/dhcpd.conf'
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dhcpd

- name: Enable dhcpd service
  systemd:
    name: dhcpd.service
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: systemctl enable dhcpd.service
  args:
    creates: '/etc/systemd/system/multi-user.target.wants/dhcpd.service'
  when: chroot

# vim: set ts=2 sw=2 et:
