---
- name: Disable getty@tty1
  systemd:
    name: getty@tty1.service
    enabled: no
    state: stopped
  when: "'container' not in ansible_env"
- name: '- when in nspawn'
  command: systemctl disable getty@tty1.service
  args:
    removes: '/etc/systemd/system/getty.target.wants/getty@tty1.service'
  when: "'container' in ansible_env"

- name: Enable serial-getty@ttyS0
  systemd:
    name: serial-getty@ttyS0.service
    enabled: yes
  when: "'container' not in ansible_env"
- name: '- when in nspawn'
  command: systemctl enable serial-getty@ttyS0.service
  args:
    creates: '/etc/systemd/system/getty.target.wants/serial-getty@ttyS0.service'
  when: "'container' in ansible_env"

# vim: set ts=2 sw=2 et:
