---
- name: Make sure /boot/<machine-id> exists
  file:
    path: '/boot/{{ ansible_machine_id }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Make sure /etc/kernel/install.d exists
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - '/etc/kernel'
  - '/etc/kernel/install.d'

- name: Mask grub and grubby
  file:
    path: '/etc/kernel/install.d/{{ item }}'
    src: '/dev/null'
    state: link
    force: yes
  with_items:
  - 20-grub.install
  - 20-grubby.install

- name: Create syslinux loader entry and menu
  copy:
    dest: '/etc/kernel/install.d/'
    src: '{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_fileglob: 'kernel/*.install'
  loop_control:
    label: '/etc/kernel/install.d/{{ item|basename }}'

- name: Set kernel command line
  template:
    dest: '/etc/kernel/cmdline'
    src: cmdline.j2
    owner: root
    group: root
    mode: 0644

- name: Install kernel
  dnf:
    name: kernel
    state: present
  tags:
  - packages

# vim: set ts=2 sw=2 et:
